### ISSUE TITLE
Is it possible to download files from a closed-access zenodo record?

### ISSUE THREAD

**Issue by MiguelRodo** [eblondel/zen4R#101]
Hi

Thanks for what should be a very useful package.

I'm just wondering if it's possible to download using `zen4R` from a closed-access Zenodo record?

If it is, then I'm not sure what I've done wrong. I generated a closed-access Zenodo record and an all-permissions PAT. I then ran the following code:

```r
zen2 <- zen4R::ZenodoManager$new(token = "<token>") # all access <token>
rec <- zen2$getRecordByDOI("10.5281/zenodo.7256569")
rec$listFiles(pretty = TRUE)
```

The above returns `NULL`, despite that the entry does have files. I then cannot download any files, of course.

**Comment by eblondel** [comment]
Thanks @MiguelRodo I will check this, afaik closed file access is a relatively new feature from Zenodo. I have to check first if it is enabled through the API model. If yes, the `listFiles` will have to be extended. I'll let you know asap

**Comment by MiguelRodo** [comment]
Right, thanks for such a prompt response!

**Comment by eblondel** [comment]
The Zenodo API documentation says "All metadata is licensed under [Creative Commons Zero](http://about.zenodo.org/terms), while the data files may be either open access and subject to a license described in the metadata or closed access and not available for download."

To make it sure, i've tried to publish a record as closed access data files in the Zenodo Sandbox platform, and tried to get back its files through the API with my token. No files are listed.

I suggest you contact the zenodo team to get more information about this. Some ticket related to this: https://github.com/zenodo/zenodo/issues/2256

**Comment by MiguelRodo** [comment]
Thanks, @eblondel! Good to know, I wouldn't have been able to figure that out.

It seems a bit odd, as you can click on files in a closed-access record and download it. Perhaps since, as you say, closed-access files are new, downloading them via the API isn't yet available. 

Thanks for highlighting that issue! It seems related, but (if I'm reading it correctly) seems more to be dealing with granting access to close-access files to others who can't download them at all, whereas in this case we want to download files we are already allowed and able to. So I might open another issue with them.

I'll close the issue now, as the question's been answered! Someone can re-open it if they notice the API starts enabling this.
