### ISSUE TITLE
getFundersByName new method support

### ISSUE THREAD

**Issue by eblondel** [eblondel/zen4R#110]
Relates to #107

**Comment by rkrug** [comment]
There is something strange happening. I would expect that the first results in less results than the second, as it filters for "Foundation" as well?

```
x <- zm$getFundersByName("Foundation")
grep("Sw", x$name) |> length()
[1] 16
zm$getFundersByName("Sw") |> nrow()
[1] 1
```

**Comment by rkrug** [comment]
Official.

**Comment by rkrug** [comment]
```
zm <- ZenodoManager$new(
  url = "https://zenodo.org/api",
  token = "XXXX",
  logger = NULL,
  keyring_backend = "env"
)
```

**Comment by eblondel** [comment]
See https://help.zenodo.org/guides/search/ for query syntax. The `getFundersByName` species a quoted value in the query. For extended use, you can use the `q` argument of `getFunders` method.

**Comment by rkrug** [comment]
OK - thanks. That helps. But when running with two search terms (first example on the site you link), I get:

```
> zm$getFunders(q = "swiss fund")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL using bad/illegal format or missing URL
```

**Comment by eblondel** [comment]
I was missing URL encoding for `q`. Please reinstall.
Btw, you will need to specify a property for searching, eg.

zm$getFunders(q = "name:swiss fund")

**Comment by rkrug** [comment]
Thanks - But I found the one I was looking for by using:

```
zm$getGrants(q = "310030_188431")
```

i.e. by searching for the grant number.

Thanks a .ot for your brilliant support!

**Comment by eblondel** [comment]
You're welcome
