### ISSUE TITLE
Zenodo to InvenioRDM - citation export methods

### ISSUE THREAD

**Issue by oggioniale** [eblondel/zen4R#136]
With zen4R version 0.9 I try to download the BibTeX citation of the record.
After a:
`rec <- zenodo$getRecordByDOI(doi)`
I do:
`rec$exportAs("BibTeX", filename = "download_files_of_7041152/7041152")`
or
`rec$exportAsBibTeX(filename = "download_files_of_7041152/7041152")`
but I obtain the same error:
`Error in open.connection(x, "rb") : HTTP error 404.`
Is it related with the changes of Zenodo APIs?

**Comment by eblondel** [comment]
Yes it is related to the change to the new Zenodo API.

**Comment by eblondel** [comment]
I had a look and changes were relatively minor. This is in implemented in a dev branch. If you want to test, install zen4R from the dev branch related to the Zenodo upgrade:

```
remotes::install_github("eblondel/zen4R", ref = "127-zenodo-invenio-rdm")
```

Let me know if it works for you

**Comment by oggioniale** [comment]
no it doesn't work

**Comment by eblondel** [comment]
Can you give me the DOI for which you try to get the citation?

**Comment by eblondel** [comment]
I've tested again and it works. On your side you try to use a filename containing a slash, it can't work.

**Comment by oggioniale** [comment]
it is a test record, the DOI is https://zenodo.org/doi/10.5281/zenodo.7034189

**Comment by eblondel** [comment]
This works:

```r
library(zen4R)
ZENODO = ZenodoManager$new()
rec = ZENODO$getRecordByConceptDOI("10.5281/zenodo.7034189")
rec$exportAsBibTeX("test") # or rec$exportAs("BibTeX", "test")
```

**Comment by oggioniale** [comment]
I do this:
```
zenodo <- zen4R::ZenodoManager$new(logger = "INFO")
rec <- zenodo$getRecordByDOI("10.5281/zenodo.7034189")
rec$exportAs("BibTeX", filename = "bib_file")
```
and your is:
```
ZENODO = ZenodoManager$new()
rec = ZENODO$getRecordByConceptDOI("10.5281/zenodo.7034189")
rec$exportAsBibTeX("test") # or rec$exportAs("BibTeX", "test")
```
In both case the output is Error in open.connection(x, "rb") : HTTP error 404.

**Comment by eblondel** [comment]
The error you reports means you installed zen4R from master, not from the dev branch:

`remotes::install_github("eblondel/zen4R", ref = "127-zenodo-invenio-rdm")`

**Comment by oggioniale** [comment]
I do this but I have the same error.

```
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 14.0

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] zen4R_0.9      magrittr_2.0.3
```

**Comment by eblondel** [comment]
I changed the package version to 0.9.9000 on the dev branch. If you can, restart R, and reinstall it, to make sure it was installed from there. This might be a package caching issue in R

**Comment by oggioniale** [comment]
Yes! Now it is work!

**Comment by eblondel** [comment]
Thanks @oggioniale for your feedback,. For now i'll keep tickets on InvenioRDM transition open, I will close them when all the work will be merged to the main branch
