### ISSUE TITLE
Action to clean Zenodo uploads ?

### ISSUE THREAD

**Issue by juldebar** [eblondel/zen4R#2]
Would it be possible to get an function which removes all uploads from Zenodo (or only some if possible to apply filters). It would be very useful when we want to remove multiple deposits at once since Zenodo GUI doesn't enable users to select and remove multiple uploads.

Later this function could be used as an action in geoflow (https://github.com/eblondel/geoflow) to clean uploads before testing new deposits.

**Comment by eblondel** [comment]
@juldebar I've pushed the missing method in zen4R. Soon i will figure out how to make it part of geoflow and let you know there

**Comment by eblondel** [comment]
I still some bricks since it sounds the Zenodo API is paging by default the depositions. So the method doesn't yet delete all records, but only those of the page returned by Zenodo.... ASAP something to deal with that I hope, and let you know.

**Comment by eblondel** [comment]
now it should ok for deleting all records. @juldebar let me know if it works for you
