### ISSUE TITLE
addCreator: allow to specify name, rather than firstname and lastname

### ISSUE THREAD

**Issue by sje30** [eblondel/zen4R#26]
Hi,

 thanks for this great package.  @nuest  and I are using it for our CODECHECK project.

Would you be interested in a PR to allow addCreator() to look like this:
```
    addCreator = function(firstname, lastname, name = paste(lastname, firstname, sep=", "),
                                                 affiliation = NULL, orcid = NULL, gnd = NULL){
      creator <- list(name = name)

```

This means that by default the API should continue to work with firstname and lastname.  However, as an alternative, we can specify name directly, which is what we'd like to do rather than be constrained by the firstname, lastname format.  I've got it working at:
https://github.com/sje30/zen4R/commit/ff2665f55ee4ecc70c4e6dbb14f6b3529ab8fe51
but have not yet added any documentation.

By mistake, I also added the same name= argument to the addContributor() function, but I'm not yet using that API.

**Comment by sje30** [comment]
p.s. what is the gnd argument for?  I couldn't find that.

**Comment by eblondel** [comment]
thanks @sje30 i look at it ASAP.  ``gnd`` is another id supported by Zenodo API https://developers.zenodo.org/#representation I didn't dig too much in it, but just sticked with the fact Zenodo API mentions it as payload property attachable to a creator (ORCID is more common indeed..).

**Comment by eblondel** [comment]
ok @sje30 @nuest i've integrated your proposal that is fine with me. Let me know

**Comment by nuest** [comment]
At a first glance, the test in line https://github.com/eblondel/zen4R/commit/555df144506387313c5b1b3ec1c533bcfb60e6c6#diff-09ea42049f1c3a35868c13b0d984d841R81 
seems not quite right. Maybe (untested!)

```
myrec$addCreator(firstname = "John", lastname = "Doe", affiliation = "Independent")
myrec$addCreator(name = "Doe, John", affiliation = "Independent")
expect_equal(myrec$metadata$creators[[1]], myrec$metadata$creators[[2]])
```

is what you mean?

But otherwise: thank you!

**Comment by eblondel** [comment]
@nuest don't worry for these tests, i have to review all of them, since others are failing (apparently due to some API changes). I've tested the feature and it works fine.

**Comment by sje30** [comment]
Thank you very much @eblondel this seems to allow me to upload name=... perfectly.

**Comment by eblondel** [comment]
Dear @sje30 I'm going soon to publish zen4R version 0.4, is it ok that I add you as contrib in package desc for this ticket? If yes, and i case you have an ORCID, can you send it to me so I can add it as well. Best, Emmanuel

**Comment by sje30** [comment]
Thank you, happy to be named.  My orcid:

https://orcid.org/0000-0001-8607-8025
