### ISSUE TITLE
Small updates to the zen4R wiki

### ISSUE THREAD

**Issue by florisvdh** [eblondel/zen4R#36]
Some small fixes have been suggested in the `master` branch of `https://github.com/florisvdh/zen4R.wiki.git`. My first-time contribution to a github wiki :smile: 

I.e. the top three commits of following commit history:

```vim
$ git log --format='%C(auto)%h (%ai)%d %s' -n 10
a18d127 (2020-08-12 16:25:35 +0200) (HEAD -> master, origin/master) Fix html anchor
5b4c5f1 (2020-08-12 16:25:18 +0200) Replace <my_concept_doi> with <my_doi>
abcb12c (2020-08-12 16:24:31 +0200) Typos & language
c02fed7 (2020-08-02 21:37:24 +0200) (upstream/master, upstream/HEAD, master_upstream) Updated Home (markdown)
3c31f47 (2020-08-02 21:28:39 +0200) create wiki
311fe16 (2020-04-14 22:43:11 +0200) add #26 #27
50d155d (2020-01-31 10:11:19 +0100) Updated Home (markdown)
4c9d4ce (2019-09-02 16:16:55 +0200) Updated Change History (markdown)
61b777d (2019-09-02 16:06:39 +0200) Updated Home (markdown)
a5462bb (2019-09-02 16:04:30 +0200) Updated Home (markdown)
```

As GitHub does not provide a web interface to the (separate) remote repo of the wiki, you need to do the merging locally and then push. It is explained here: https://gist.github.com/larrybotha/10650410#merging-changes

So this should work:

```bash
$ git clone https://github.com/eblondel/zen4R.wiki.git
$ cd zen4R.wiki

# squashing all FREPO changes
$ git pull https://github.com/florisvdh/zen4R.wiki.git master

$ git push origin master
```

**Comment by florisvdh** [comment]
_[note to self: contributing to a wiki]_

1. - _fork the original repo with the wiki_
    - _initialize the empty wiki in the fork with an empty home page (see also [here](https://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki/56480628#56480628))_
    - _locally clone the original wiki-repo (originalrepoURL.wiki.git). It cannot be consulted at GitHub website (hence you can't make pull requests). rename the master branch to master_upstream, rename this remote to upstream_
2. _make a new local master branch and make commits_
3. _add a second remote, named 'origin', pointing to the forked wiki-repo (forkedrepoURL.wiki.git)._
4. _`git push -u origin master --force`_
5. _communicate about it_

**Comment by eblondel** [comment]
@florisvdh will have a look asap to your changes. thanks for contributing

**Comment by eblondel** [comment]
merged
