### ISSUE TITLE
download_zenodo() issue with md5sum 

### ISSUE THREAD

**Issue by ivan-paleo** [eblondel/zen4R#38]
I have some integrity issues when I download the files of a Zenodo record.

If I do that for example:
`zen4R::download_zenodo("10.5281/zenodo.3632517")`
the files are downloaded correctly but I have warnings about the md5sums that do not match.

Looking into the files, it seems that empty lines have been inserted everywhere, leading to different files from the originals (compare e.g. "Script3_plots.Rmd" when downloaded through zen4R and when downloaded directly from Zenodo).

Any idea what's causing it?

**Comment by eblondel** [comment]
thanks @ivan-paleo for reporting, i fixed download.file call, can you reinstall package and retry? It should work now

**Comment by ivan-paleo** [comment]
@eblondel That's the quickest fix ever! 
Thank you very much for the great tool.

**Comment by eblondel** [comment]
@ivan-paleo thanks you're welcome. Feel free to report other issues.
