### ISSUE TITLE
addRelatedIdentifier

### ISSUE THREAD

**Issue by oggioniale** [eblondel/zen4R#47]
Dear eblondel,
I am continuing to work with your library (which I find very interesting).
In particular I would like to add to a record, not yet published, a Related Identifiers (in particular [LSID](https://en.wikipedia.org/wiki/LSID)).
I have successfully added first LSID with
```
> recordAbetiSoprani$addRelatedIdentifier('cites', 'urn:lsid:faunaeur.org:taxname:229693')
> zenodo$depositRecord(recordAbetiSoprani)
```

but if I try to add other outputs it is:
```
> recordAbetiSoprani$addRelatedIdentifier('cites', 'urn:lsid:faunaeur.org:taxname:186816')
[1] FALSE
```

how can I solve it? Can I load arrays of related identifiers?
thanks

**Comment by eblondel** [comment]
Hi @oggioniale so far i've managed unicity of resource by identifier types, so at now multiple resources for a same type (eg 'cites') is not possible. It might have been a limitation in Zenodo at the time I did it in that way, I have to double check if we can do what you want in Zenodo, in that case I will remove the controls in the R function ``addRelatedIdentifier``

**Comment by oggioniale** [comment]
thanks!!
Please. Let me know the rusult of your check.

**Comment by eblondel** [comment]
Well, it sounds more like a but on zen4R. I've just pushed a commit that should solve the issue.

**Comment by oggioniale** [comment]
I've just to reinstall the app by `devtools::install_github("eblondel/zen4R")` and I reloded the record.
After `> recordAbetiSoprani$addRelatedIdentifier('cites', 'urn:lsid:faunaeur.org:taxname:186816')` but the responce is again `[1] FALSE`

Any suggestion?

**Comment by eblondel** [comment]
make sure you get again your record in a clean r session, especially for
rstudio otherwise you might keep going with the previous object

Le lun. 30 nov. 2020 18:53, Alessandro Oggioni <notifications@github.com> a
écrit :

**Comment by oggioniale** [comment]
sure thanks a lot now it is possible to upload more than one Releted Identifier.
