### ISSUE TITLE
Add information on installation for Linux/OSX to documentation

### ISSUE THREAD

**Issue by simschul** [eblondel/zen4R#49]
Hi, 
thanks a lot for this nice package. 

One minor issue: 
On my Ubuntu machine installation via `install.packages(zen4R)` or `install_github('eblondel/zen4R')` failed because of problems with the package `sodium`. With the help from [here](https://github.com/jeroen/sodium#readme), I could solve the problems by installing libsodium with `sudo apt-get install -y libsodium-dev` (command different for other OS). 

Maybe you could add some information (or the upper link) to you online documentation?

Thanks, 
Simon

**Comment by eblondel** [comment]
Thanks Simon, i've added some instructions at https://github.com/eblondel/zen4R/wiki#install_guide
