### ISSUE TITLE
Constructor creates null object

### ISSUE THREAD

**Issue by antaldaniel** [eblondel/zen4R#51]
After re-reading your wiki about 10 times, and trying to replicate your examples, I do not seem to be able to create any Zenodo records. 

`zenodo_sandbox <- ZenodoManager$new(
  url = "http://sandbox.zenodo.org/api",
  token = sandbox_pat, 
  logger = "INFO"
)`

[zen4R][INFO] ZenodoManager - Successfully connected to Zenodo with user token 

`my_empty_rec <- zenodo_sandbox$createEmptyRecord()`

[zen4R][INFO] ZenodoManager - Successful record deposition 

I don't know what this message means, because my depositions remain NULL

`zenodo_sandbox$getDepositions()`
returns NULL

Something did got created: 

`class ( my_empty_rec )`
"ZenodoRecord" "zen4RLogger"  "R6"  
and is.null(my_empty_rec) is not false. 

I go on with your README, which says that it is possible to create and deposit an empty record, ready for editing.This method should  return an object of class ZenodoRecord for which an internal id and a DOI have been pre-defined by Zenodo.

`myrec <- ZenodoRecord$new()
class(myrec)
"ZenodoRecord" "zen4RLogger"  "R6"  `

myrec is not NULL, but

`myrec$id`
is NULL and 
`myrec$setTitle("my R package")`

does not appear to change anything on the object, and I do not even know if this is an object, and not an environment.  
How can I check if this object is created?  How should I interact with this object?  How should I be able that indeed an ID was created?  How could I change the title of this  object, or do anything to see if it is a an object at all?

`myrec <- zenodo_sandbox$depositRecord(myrec)`
gives a success report
[zen4R][INFO] ZenodoManager - Successful record deposition 

But in fact, my Zenodo (sandbox) profile remains as empty as it was.   I am getting a lot of success messages, but it seems to me that I am pushing around an empty object.

I also tried the alternative method, which also appears to create an empty object only, too.  Your README says " An alternate method is to create a local empty record (not deposited on Zenodo) doing:"

`my_empty_rec <- zenodo_sandbox$createEmptyRecord()`
[zen4R][INFO] ZenodoManager - Successful record deposition 
In my RStudio a my_empty_rec environment appears, but not an object. 

I duly go on without any error message with the rest of your example: 

`my_empty_rec$setTitle("my R package")
my_empty_rec$setDescription("A description of my R package")
`

No error messages, but 
my_empty_rec$title  remains NULL

`my_empty_rec$getClass() `
<ZenodoRecord> object generator
  Inherits from: <zen4RLogger>
  Public:
    conceptdoi: NULL
    conceptrecid: NULL
    created: NULL
    doi: NULL
    doi_url: NULL
    files: list
    id: NULL
    links: list
    metadata: list
    modified: NULL
    owner: NULL
    record_id: NULL
    state: NULL
    submitted: FALSE
    title: NULL
    initialize: function (obj = NULL, logger = "INFO") 
    prereserveDOI: function (prereserve) 
    setDOI: function (doi) 
    getConceptDOI: function () 
    getFirstDOI: function () 
    getLastDOI: function () 
    getVersions: function () 
    setUploadType: function (uploadType) 
    setPublicationType: function (publicationType) 
    setImageType: function (imageType) 
    setPublicationDate: function (publicationDate) 
    setEmbargoDate: function (embargoDate) 
    setTitle: function (title) 
    setDescription: function (description) 
    setAccessRight: function (accessRight) 
    setAccessConditions: function (accessConditions) 
    addCreator: function (firstname, lastname, name = paste(lastname, firstname, 
    removeCreator: function (by, property) 
    removeCreatorByName: function (name) 
    removeCreatorByAffiliation: function (affiliation) 
    removeCreatorByORCID: function (orcid) 
    removeCreatorByGND: function (gnd) 
    addContributor: function (firstname, lastname, type, affiliation = NULL, orcid = NULL, 
    removeContributor: function (by, property) 
    removeContributorByName: function (name) 
    removeContributorByAffiliation: function (affiliation) 
    removeContributorByORCID: function (orcid) 
    removeContributorByGND: function (gnd) 
    setLicense: function (licenseId) 
    setVersion: function (version) 
    setLanguage: function (language) 
    addRelatedIdentifier: function (relation, identifier) 
    removeRelatedIdentifier: function (relation, identifier) 
    setReferences: function (references) 
    addReference: function (reference) 
    removeReference: function (reference) 
    setKeywords: function (keywords) 
    addKeyword: function (keyword) 
    removeKeyword: function (keyword) 
    addSubject: function (term, identifier) 
    removeSubject: function (by, property) 
    removeSubjectByTerm: function (term) 
    removeSubjectByIdentifier: function (identifier) 
    setNotes: function (notes) 
    setCommunities: function (communities) 
    addCommunity: function (community) 
    removeCommunity: function (community) 
    setGrants: function (grants) 
    addGrant: function (grant) 
    removeGrant: function (grant) 
    setJournalTitle: function (title) 
    setJournalVolume: function (volume) 
    setJournalIssue: function (issue) 
    setJournalPages: function (pages) 
    setConferenceTitle: function (title) 
    setConferenceAcronym: function (acronym) 
    setConferenceDates: function (dates) 
    setConferencePlace: function (place) 
    setConferenceUrl: function (url) 
    setConferenceSession: function (session) 
    setConferenceSessionPart: function (part) 
    setImprintPublisher: function (publisher) 
    setImprintISBN: function (isbn) 
    setImprintPlace: function (place) 
    setPartofTitle: function (title) 
    setPartofPages: function (pages) 
    setThesisUniversity: function (university) 
    addThesisSupervisor: function (firstname, lastname, affiliation = NULL, orcid = NULL, 
    removeThesisSupervisor: function (by, property) 
    removeThesisSupervisorByName: function (name) 
    removeThesisSupervisorByAffiliation: function (affiliation) 
    removeThesisSupervisorByORCID: function (orcid) 
    removeThesisSupervisorByGND: function (gnd) 
    exportAs: function (format, filename) 
    exportAsBibTeX: function (filename) 
    exportAsCSL: function (filename) 
    exportAsDataCite: function (filename) 
    exportAsDublinCore: function (filename) 
    exportAsDCAT: function (filename) 
    exportAsJSON: function (filename) 
    exportAsJSONLD: function (filename) 
    exportAsGeoJSON: function (filename) 
    exportAsMARCXML: function (filename) 
    exportAsAllFormats: function (filename) 
    listFiles: function (pretty = TRUE) 
    downloadFiles: function (path = ".", parallel = FALSE, parallel_handler = NULL, 
    clone: function (deep = FALSE) 
  Private:
    fromList: function (obj) 
  Parent env: <environment: namespace:zen4R>
  Locked objects: TRUE
  Locked class: FALSE
  Portable: TRUE

But if I go on, I do not get error messages at all:

`
my_empty_rec$setUploadType("software")

my_empty_rec$addCreator(firstname = "John", lastname = "Doe", affiliation = "Independent", orcid = "0000-0000-0000-0000")
`

I do not what is the expected behavior here.  I assumed that an object should have been created and its properties set by methods, but I do not think that happens, and it would be good to see somewhere an example what should happen here. But anyway, at the end of your example.

`
my_new_rec <- zenodo_sandbox$depositRecord(my_empty_rec)
`
Gives an error:
Error in !data[["submitted"]] : invalid argument type

I do not know what is submitted, but to me everything seems to be NULL..

I am sorry if I am asking a trivial question, I do not count myself a complete novice in R with several CRAN packages, but after a working day I just cannot figure out anything in the package, and I do not even know what should be the expected outcome, as there are so many success messsages but a complete failure in trying to deposit anything.

Is there anywhere a blogpost, or a presentation that would show how to publish the iris dataset with your package?

**Comment by eblondel** [comment]
@antaldaniel can you paste your sessionInfo? it will help me investigate it. Thanks

**Comment by eblondel** [comment]
Hi @antaldaniel no need to apology; Good to see that now it works! thanks for your suggestion of extra sentence I will put it in the wiki!
