### ISSUE TITLE
Upload a release from GitHub to Zenodo 

### ISSUE THREAD

**Issue by BatoolMM** [eblondel/zen4R#52]
As you might already know, there's [a nice integration between Zenodo and GitHub](https://guides.github.com/activities/citable-code/). Once a release is created in GH, it can be linked to Zenodo with few clicks. I wonder if we can possibly do the same using `zen4R`or from within R Studio. I mean is there a way to link a release of an R project from GH to Zenodo with `zen4R`? Thanks

**Comment by eblondel** [comment]
that's nothing I thought about, but it could be nice to have it.

**Comment by eblondel** [comment]
You might want to dig around Github actions to see if you configure a Github action workflow triggered on release, that would run R script with zen4R to publish on Zenodo.
