### ISSUE TITLE
Upload large files via new API

### ISSUE THREAD

**Issue by noamross** [eblondel/zen4R#53]
Per the Zenodo API guide (https://developers.zenodo.org/#quickstart-upload), the old API supports uploads up to 100MB but the new one has no such limitation.  Would it be possible to implement upload via the new PUT API?

**Comment by eblondel** [comment]
Thanks @noamross for this suggestion, i was not aware of this new API. I've commited some code on master. Great if you can test it on huge files. I've tested it on small files and it seems to work. Let me know
