### ISSUE TITLE
Add print method(s) for ZenodoRecord

### ISSUE THREAD

**Issue by ThierryO** [eblondel/zen4R#66]
Currently the user gets the list of public elements, which can be intimidating. Maybe display the citation instead? E.g. the bibtex format?

**Comment by eblondel** [comment]
Thanks @ThierryO yes it's on the wishlist to improve the print method associated to zenodo records. Not sure if the bibtex format will be implemented, but the idea is to get a print of all metadata elements as handled in the Zenodo API model.

**Comment by eblondel** [comment]
@ThierryO i've done a 1st implementation with https://github.com/eblondel/zen4R/commit/2695d8466cede33f8b0f7c2b17b3af8001096db6

By default, the print uses an "internal" format, for which I tried to make a first version, but that deserves some improvements (probably to have it implemented recursively). The argument "format" allows you to specify other formats among those supported as Zenodo export formats. This is only available for **published** records (ie that have already been published on Zenodo with a DOI).

Example (with the BibTeX printing):

```{r}
zen = ZenodoManager$new(logger = "DEBUG")
rec = zen$getRecordByConceptDOI("10.5281/zenodo.2547036")
rec #see the default printing
rec$print(format = "BibTeX") #printing as BibTeX
```

Let me know if it is what you had in mind

**Comment by ThierryO** [comment]
This is much more useful. The bibtex seems fine as is. The default provides alot (probably all) information and is a bit harder to scan for the information one is looking for. Maybe add the fields used in the bibtex format at the bottom of the default printing with a nicer formatting?

Here are a few more examples. I noticed that the default printing displays the version as `NULL`
```
# R package
rec = zen$getRecordByDOI("10.5281/zenodo.6368129")
rec #see the default printing
rec$print(format = "BibTeX")

# publication with a lot of files
rec = zen$getRecordByDOI("10.5281/zenodo.5838468")
rec #see the default printing
rec$print(format = "BibTeX")
```

**Comment by eblondel** [comment]
Concerning the `version`, I have to see in the API why the it is handled as root property in the record, as in the metadata exchange model it is not used. What is used for the `version` is the one set in the `metadata` property.

**Comment by eblondel** [comment]
i'm closing this one, as a first implementation is available with choices for record export formats for published records. This will be part of next CRAN release.
