### ISSUE TITLE
Rate limit for deleting files

### ISSUE THREAD

**Issue by ThierryO** [eblondel/zen4R#67]
When creating a new version with `delete_latest_files = TRUE`, I'm hitting a Zenodo rate limit (100 deletions per 1 min)

Maybe slow the loop down by adding `Sys.sleep(0.6)` to https://github.com/eblondel/zen4R/blob/ecbd483de65c0660684c97b97d2ee2442c04e64a/R/ZenodoManager.R#L755

**Comment by eblondel** [comment]
@ThierryO I see you set 0.6 as sleeping time, any reason for this value? did you test other values?

**Comment by ThierryO** [comment]
1 min per 100 requests = 60 sec / 100 requests = 0.6 sec / request. So setting sleeping time to 0.6 makes sure that you never do more than 100 request per minute.

I've tried different values. 0.3 is too short, 0.4 worked for https://zenodo.org/record/5838468.

**Comment by ThierryO** [comment]
I uses this code

```
zen_files <- zenodo$getFiles(myrec$id)
map_chr(zen_files, "id") %>%
  sort() %>%
  walk(
    function(fid) {
      message(fid)
      zenodo$deleteFile(recordId = myrec$id, fileId = fid)
      Sys.sleep(0.4)
    }
  )
```
