### ISSUE TITLE
zenodo$uploadFile(path, myrec$id) returning atomic vector error

### ISSUE THREAD

**Issue by nealhaddaway** [eblondel/zen4R#69]
AMAZING package! I've just run into a file upload problem.

When running the code `zenodo$uploadFile(path, myrec$id)` to upload a file to a record (that I know exists) I get the following error: 'Error in record$id : $ operator is invalid for atomic vectors'

`myrec$id` returns a real id, so I'm not sure what the problem is. I've already called 'zenodo' with:
`zenodo <- ZenodoManager$new(
    token = 'token', 
    logger = "INFO"
  )`

Almost certainly my fault, but I can't find a solution. Thank you so much!

**Comment by eblondel** [comment]
Is the record a deposit under edition, or a record already published with a DOI?

**Comment by nealhaddaway** [comment]
Thanks, Emmanuel. It's not yet published (so no DOI). I understood that I couldn't publish without uploading a file.
________________________________

**Comment by eblondel** [comment]
Ok I see now. You use `zenodo$uploadFile(path, myrec$id)` assuming `myrec$id` for the second argument. The latter should be an object of class `ZenodoRecord` and not the id. You should instead use `zenodo$uploadFile(path, myrec)` meaning `zenodo$uploadFile(path, record = myrec)`. There is a legacy `recordId` in the function (as 3rd argument) but it's deprecated as it uses the old upload API.
This should fix your issue, let me know

**Comment by nealhaddaway** [comment]
Ah perfect - thank you so much!
Neal
________________________________
