### ISSUE TITLE
setEmbargoDate() returns error

### ISSUE THREAD

**Issue by nealhaddaway** [eblondel/zen4R#70]
When creating a record, I attempt to `setEmbargoDate` as follows:

`myrec$setEmbargoDate(strftime(presenter_data$time_start, "%Y-%m-%dT%H:%M:%S%z"))`

My embargo date is a properly formatted ISO-compliant date, but I get the following error:

"Error in myrec$setEmbargoDate(strftime(presenter_data$time_start, "%Y-%m-%dT%H:%M:%S%z")) : 
  The embargo date should be a 'Date' object"

If I use the following date format it appears to function to an extent, but throws back an error:

`myrec$setEmbargoDate(as.Date(presenter_data$time_start))`
where `presenter_data$time_start` is "2022-02-24 12:30:00". I then get the following error:
"Error in .class1(object) : object 'publicationDate' not found"

I've tried various different formats, but nothing is working. Am I doing something stupid (I probably am, sorry!)

Thanks!

**Comment by eblondel** [comment]
nothing stupid, but a wrong copy paste on my side, and no enough tests to make sure this method worked :-) Now it should be fixed. Can you test?

**Comment by nealhaddaway** [comment]
ooh thanks - might be a problem on my end, but I'm getting a time out when trying to connect:

"Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [zenodo.org] Operation timed out after 10000 milliseconds with 0 out of 0 bytes received"

**Comment by nealhaddaway** [comment]
Sorry - my bad, hadn't updated some dependencies. Checking now.

**Comment by nealhaddaway** [comment]
Bingo! Thanks so much, that works - LOVE the package, by the way. It's gonna save us SO much time uploading conference metadata!

**Comment by nealhaddaway** [comment]
Wait - thought it was fixed. No error, but the record hasn't registered the embargo date. And I get a new error uploading a file now:

"[zen4R][INFO] ZenodoManager - Using new file upload API with bucket: https://zenodo.org/api/files/48495b3f-b43c-434a-95fe-c8e62413af8a 
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL_write() returned SYSCALL, errno = 32"

**Comment by nealhaddaway** [comment]
Although I may have forgotten to specify the access should be embargoed as well as providing a date...

**Comment by nealhaddaway** [comment]
Yup - my bad. With setAccessRight that works a charm (now to fix the upload error... probably my fault). Love the package thanks so much!
