### ISSUE TITLE
getDepositionByDOI() errors when Zenodo returns a 404

### ISSUE THREAD

**Issue by ThierryO** [eblondel/zen4R#76]
I'm getting `Error in result$doi : $ operator is invalid for atomic vectors`

```
zenodo <- ZenodoManager$new(token = key_get("zenodo"))
zenodo$getDepositionByDOI("10.5281/zenodo.5792949")
```
The line below fails because `result <- list(message = "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", 
    status = 404L)`

https://github.com/eblondel/zen4R/blob/7320f3c89733c2752821e49bf3686913fefa4b41/R/ZenodoManager.R#L536

**Comment by eblondel** [comment]
thanks @ThierryO will look at it asap, first to see if I can reproduce it. Is it something that you experiment permanently? I'm asking because it looks like a temporary error.

**Comment by ThierryO** [comment]
This code used to work back in January. I'm trying to upload a new version of an existing deposit.
