### ISSUE TITLE
Progress when uploading a file?

### ISSUE THREAD

**Issue by eblondel** [eblondel/zen4R#95]
### Discussed in https://github.com/eblondel/zen4R/discussions/94

<div type='discussions-op-text'>

<sup>Originally posted by **rkrug** August 12, 2022</sup>
I might be missing it - but is there a way of seeing the progress when uploading a file? I have to upload 128 25GB files, and it would be nice to see the progress while uploading.</div>

**Comment by eblondel** [comment]
@rkrug FYI this is now integrated into zen4R.

**Comment by rkrug** [comment]
Great - thanks a lot. Will try it put soon.
